In [1]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense

In [2]:
(X_train,y_train),(X_test,y_test)=mnist.load_data()

In [3]:
X_train=X_train.reshape((X_train.shape[0]),X_train.shape[1],X_train.shape[2],1)

In [4]:
X_test=X_test.reshape((X_test.shape[0]),X_test.shape[1],X_test.shape[2],1)

In [5]:
print(X_train.shape)

(60000, 28, 28, 1)


In [6]:
print(X_test.shape)

(10000, 28, 28, 1)


In [7]:
print(X_test.shape)

(10000, 28, 28, 1)


In [8]:
X_train=X_train/255
X_test=X_test/255

In [9]:
print(X_train)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [10]:
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [11]:
print(y_train)

[5 0 4 ... 5 6 8]


In [12]:
print(y_test)

[7 2 1 ... 4 5 6]


In [13]:
model=Sequential()

In [14]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))

In [15]:
model.add(MaxPool2D(2,2))

In [16]:
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [17]:
model.add(Dense(10,activation='softmax'))

In [18]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [19]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 22s 11ms/step - loss: 0.1628 - accuracy: 0.9507
Epoch 2/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0539 - accuracy: 0.9837
Epoch 3/10
1875/1875 [==============================] - 23s 12ms/step - loss: 0.0350 - accuracy: 0.9889
Epoch 4/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0243 - accuracy: 0.9919
Epoch 5/10
1875/1875 [==============================] - 28s 15ms/step - loss: 0.0158 - accuracy: 0.9949
Epoch 6/10
1875/1875 [==============================] - 22s 12ms/step - loss: 0.0110 - accuracy: 0.9967
Epoch 7/10
1875/1875 [==============================] - 21s 11ms/step - loss: 0.0088 - accuracy: 0.9972
Epoch 8/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0064 - accuracy: 0.9979
Epoch 9/10
1875/1875 [==============================] - 20s 11ms/step - loss: 0.0054 - accuracy: 0.9983
Epoch 10/10
1875/1875 [==============================] - 19s 10m

In [20]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 2s 7ms/step - loss: 0.0589 - accuracy: 0.9858


[0.058904290199279785, 0.98580002784729]