<a href="https://colab.research.google.com/github/Shubham-Das-Coder/Deep_Learning/blob/main/Loss_Or_Cost_Function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=([0.30,0.70,1.0,0.0,0.5])

In [2]:
def mae(y_true,y_predicted): #Mean absolute error
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        print(yt,yp)

In [3]:
mae(y_true,y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [4]:
def mae(y_true,y_predicted): #Mean absolute error
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("Total error:",total_error)
    mae=total_error/len(y_true)
    return mae

In [5]:
mae(y_true,y_predicted)

Total error: 2.5


0.5

In [6]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [7]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [8]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [9]:
np.log([0.0000000000000001])

array([-36.84136149])

In [10]:
epsilon=1e-15

In [11]:
y_predicted

array([1, 1, 0, 0, 1])

In [12]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [13]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [14]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [15]:
np.log(y_predicted)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([  0.,   0., -inf, -inf,   0.])

In [16]:
-np.mean((y_true*np.log(y_predicted_new))+((1-y_true)*np.log(1-y_predicted_new))) #Log loss function

TypeError: ignored

In [17]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean((y_true*np.log(y_predicted_new))+((1-y_true)*np.log(1-y_predicted_new))) #Log loss function

In [18]:
log_loss(y_true,y_predicted)

TypeError: ignored